site_name: pyAlicat

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tooltips
    - content.code.select
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
repo_name: ulfsri/pyalicat
repo_url: https://github.com/ulfsri/pyalicat
plugins:
- search
- mkdocstrings
nav:
  - Home: index.md
  - Code Reference:
    - Device: device-reference.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/ulfsri"  target="_blank" rel="noopener">FSRI</a>
